### ISSUE TITLE
Enable collapsible table templates in GCcollab Wiki

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/concierge#48]
Right now, the below code renders as collapsible in GCpedia. In GCcollab wiki, it doesn't.
![image](https://user-images.githubusercontent.com/29754185/39005955-9520404e-43cf-11e8-8703-962362b7dcf1.png)

Users would like collapsible table templates added to GCcollab wiki.

**Comment by klecuyer** [comment]
https://support.gctools-outilsgc.ca/helpdesk/tickets/3134

**Comment by klecuyer** [comment]
@Phanoix was this a part of fixes you were still doing to the wiki, or is this a new add-in? Just trying to determine if I should close or not.

**Comment by Troy-Lawson** [comment]
added the same collapsible table code from gcpedia so in theory this should work now. give it a try and let me know?

**Comment by Troy-Lawson** [comment]
closing, will reopen if still a problem

**Comment by klecuyer** [comment]
@Troy-Lawson Joy tested this and reported it as still broken:
I copied the wiki table code from http://www.gcpedia.gc.ca/wiki/CSPS_Classroom_2020_-_FAQ_EN into https://wiki.gccollab.ca/User:Joy.moskovic/test and you can see that the show / hide feature does not work.
